stages:

  pretrain:
    cmd: clj src/pretrain.clj data/iris.csv data/lookup-table.edn data/train.arrow data/test.arrow
    deps:
    - src/pretrain.clj
    - data/iris.csv
    outs:
    - data/lookup-table.edn
    - data/train.arrow
    - data/test.arrow

  train:
    cmd: python3 src/train.py data/train.arrow model.pkl
    deps:
    - src/train.py
    - data/train.arrow
    params:
    - train.class_weight
    outs:
    - model.pkl

  evaluate:
    cmd: python3 src/evaluate.py model.pkl data/test.arrow metrics.json evaluation importance.png
    deps:
    - src/evaluate.py
    - model.pkl
    - data/test.arrow
    metrics:
    - metrics.json:
        cache: false
    plots:
    - evaluation/importance.png
    - evaluation/plots/confusion_matrix.json:
        cache: false
        template: confusion
        x: actual
        y: predicted

  predict:
    cmd: clj -A:py src/predict.clj model.pkl data/lookup-table.edn data/predictions.csv
    deps:
    - src/predict.clj
    - model.pkl
    - data/lookup-table.edn
    outs:
    - data/predictions.csv
