stages:

  prep:
    cmd: clj -M:std src/prep.clj ${files.source.iris} ${files.prep.label-lookup} ${files.prep.train} ${files.prep.test}
    deps:
      - src/prep.clj
      - ${files.source.iris}
    outs:
      - ${files.prep.label-lookup}
      - ${files.prep.train}
      - ${files.prep.test}

  train:
    cmd: python3 src/train.py ${files.prep.train} ${files.dvc.params} ${files.train.model}
    deps:
      - src/train.py
      - ${files.prep.train}
    params:
      - ${files.dvc.params}:
        - random_forest
    outs:
      - ${files.train.model}

  evaluate:
    cmd: python3 src/evaluate.py ${files.train.model} ${files.prep.label-lookup} ${files.prep.test} ${files.dvc.metrics} ${files.dvc.live} ${files.evaluate.feat-importance} ${files.evaluate.confusion-matrix}
    deps:
      - src/evaluate.py
      - ${files.train.model}
      - ${files.prep.label-lookup}
      - ${files.prep.test}
    metrics:
      - ${files.dvc.metrics}:
          cache: false
    plots:
      - ${files.dvc.live}/plots/images/${files.evaluate.feat-importance}
      - ${files.dvc.live}/plots/sklearn/${files.evaluate.confusion-matrix}.json:
         cache: false
         template: confusion
         x: actual
         y: predicted
         x_label: Actual class
         y_label: Predicated class

  predict:
    cmd: clj -M:std:jni src/predict.clj ${files.train.model} ${files.prep.label-lookup}  ${files.predict.predictions}
    deps:
      - src/predict.clj
      - ${files.train.model}
      - ${files.prep.label-lookup}
    outs:
      - ${files.predict.predictions}
