stages:

  prepare:
    cmd: clj src/prepare.clj data/iris.csv data/label-lookup.json data/train.arrow data/test.arrow
    deps:
    - src/prepare.clj
    - data/iris.csv
    outs:
    - data/label-lookup.json
    - data/train.arrow
    - data/test.arrow

  train:
    cmd: python3 src/train.py data/train.arrow model.pkl
    deps:
    - src/train.py
    - data/train.arrow
    params:
    - train.class_weight
    outs:
    - model.pkl

  evaluate:
    cmd: python3 src/evaluate.py model.pkl data/label-lookup.json data/test.arrow metrics.json evaluation importance.png
    deps:
    - src/evaluate.py
    - data/label-lookup.json
    - model.pkl
    - data/test.arrow
    metrics:
    - metrics.json:
        cache: false
    plots:
    - evaluation/importance.png
    - evaluation/plots/sklearn/confusion_matrix.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
        x_label: Actual class
        y_label: Predicated class

  predict:
    cmd: clj -A:py src/predict.clj model.pkl data/label-lookup.json data/predictions.csv
    deps:
    - src/predict.clj
    - model.pkl
    - data/label-lookup.json
    outs:
    - data/predictions.csv
