stages:

  pretrain:
    cmd: clj pretrain.clj
    deps:
      - pretrain.clj
      - iris.csv
    outs:
      - lookup-table.edn
      - train.arrow
      - test.arrow

  train:
    cmd: python train.py
    deps:
      - train.py
      - train.arrow
      - test.arrow
    outs:
      - model.pickle
    metrics:
      - eval.json
    params:
      - train.class_weight

  predict:
     cmd: clj -A:py predict.clj
     deps:
       - predict.clj
       - model.pickle
       - lookup-table.edn
     outs:
       - predictions.csv