files:

  dvc: 
    params: src/params.py
    metrics: metrics.json
    live: evaluation

  source:
    iris: data/iris.csv

  prep: 
    label-lookup: data/label-lookup.json
    train: data/train.arrow
    test: data/test.arrow

  train:
    model: model.pkl

  evaluate:
    live-dir: evaluation
    importance: importance.png
    confusion-matrix: confusion_matrix

  predict:
    predictions: data/predictions.csv
